version: "3"
services:
  go_tests:
    image: golang:1.13
    volumes:
      - .:$GOPATH/src/httpmonitor/
    working_dir: $GOPATH/src/httpmonitor/
    command: bash -c "go run main.go --threshold=5 & go run tools/loggenerator.go > /tmp/access.log"
